### PR TITLE
feat(clang-tidy, colcon-build): make CMAKE_BUILD_TYPE optional

### PR DESCRIPTION
**Pull request by kenji-miyake**
## Description

`Release` can overlook some mistakes.

Related: https://github.com/autowarefoundation/autoware.universe/issues/1959

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kenji-miyake** [comment]
From this comment, I'll use `Debug`.
https://github.com/autowarefoundation/autoware.universe/issues/1959#issuecomment-1259351708

**Comment by ambroise-arm** [comment]
What I had in mind was adding a step to also compile and run tests with `Debug`, not replacing `Release`. I believe continuing to test `Release` is important because it reflects the state that the end application will (or at least should) be using.
Doing both compilations and tests all the time would probably be wasteful in time and resources. So maybe only on the nightly trigger?

But I was checking locally the result of `colcon test` on the whole autoware repository and I get a lot of packages failing:
```
14 packages had test failures: autoware_auto_control_msgs autoware_auto_geometry_msgs autoware_auto_mapping_msgs autoware_auto_perception_msgs autoware_auto_planning_msgs autoware_auto_system_msgs autoware_auto_vehicle_msgs autoware_control_msgs autoware_localization_msgs autoware_sensing_msgs behavior_velocity_planner freespace_planning_algorithms tamagawa_imu_driver velodyne_msgs
```
So maybe it's not such a good idea to add `Debug` right now. I think it would be good to look into each failure and fixing those first before adding it. For example, `behavior_velocity_planner` failed with:
```
2: occlusion_spot-test: /usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:117: Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType Eigen::DenseCoeffsBase<Derived, 0>::operator()(Eigen::Index, Eigen::Index) const [with Derived = Eigen::Matrix<float, -1, -1>; Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType = const float&; Eigen::Index = long int]: Assertion `row >= 0 && row < rows() && col >= 0 && col < cols()' failed.
```
which doesn't look great.

**Comment by kenji-miyake** [comment]
@ambroise-arm Thank you for your comment. Okay, then I'll make it an option.

**Comment by ambroise-arm** [comment]
@kenji-miyake Yep, looks good!

**Comment by kenji-miyake** [comment]
Thanks. I'll test it in `autoware.universe`.

**Comment by kenji-miyake** [comment]
Seems it's working.
https://github.com/autowarefoundation/autoware.universe/pull/1965

**Pull request merged**
