### PR TITLE
build: disable internet access during the build step

### PR DESCRIPTION
**Pull request by esteve**
## Description

This PR disables access to internet with `unshare` so that we make sure that packages do not download any artifacts during the build step.

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by esteve** [comment]
@mitsudome-r @xmfcx I don't know who should be assigned as a reviewer for this PR. The spell check test is failing because it's waiting for https://github.com/tier4/autoware-spell-check-dict/pull/585

**Comment by HansRobo** [comment]
@esteve 
sorry for late response.
The changes seem to be fine to me, but I am testing them just to be sure.
https://github.com/HansRobo/autoware.universe/actions/runs/6031849665

Please wait for a while

**Comment by HansRobo** [comment]
It seems that there are still packages in A that require external access during build.
ref: [`tensorrt_yolo` tries to download a file via internet and its build fails](https://github.com/HansRobo/autoware.universe/actions/runs/6032193009/job/16366985698#step:7:19815)

@esteve 
How about extracting to the step of `/etc/nsswitch.conf` setting change and setting restoration workflow and adding an argument of `colcon-build` action that controls whether it can be executed or not, so as not to be a destructive change? (e.g. `allow_internet_acess_during_building`)

**Comment by esteve** [comment]
@HansRobo thanks for your review. I prefer not to add the option to disable this check, otherwise I worry that developers will bypass it and we won't notice (we don't have similar options for any of the other required checks). In any case, this PR is not meant to be merged as is right now, but once all the packages have been patched to not download artifacts by default (like tensorrt_yolo, for example), this PR can be merged and ensure that future packages don't access the network. The patch for tensorrt_yolo can be found at https://github.com/autowarefoundation/autoware.universe/pull/3142, I'm tracking all the packages that need patching in https://github.com/autowarefoundation/autoware.universe/issues/3137

I created a test PR (see https://github.com/autowarefoundation/autoware.universe/pull/4375) to demonstrate how a PR that accesses the network would fail.

**Comment by HansRobo** [comment]
@esteve 
I see. Thank you for providing the situation about this pull-request!

It's ok to merge this pull-request after finishing https://github.com/autowarefoundation/autoware.universe/pull/3142 and https://github.com/autowarefoundation/autoware.universe/issues/3137. 
So, please don't mind [my advice to add an option to allow internet connection](https://github.com/autowarefoundation/autoware-github-actions/pull/241#issuecomment-1700403150).

Could you please let me know, when everything is complete?
Let's merge this pull-request then!

**Comment by esteve** [comment]
@HansRobo we have merged https://github.com/autowarefoundation/autoware/pull/3375 and will merge https://github.com/autowarefoundation/autoware-documentation/pull/345 soon. In the mean time between https://github.com/autowarefoundation/autoware/pull/3375 was submitted and it was merged, https://github.com/autowarefoundation/autoware.universe/pull/3143 has conflicts because new artifacts were added, so I propose we merge this PR as soon as possible to avoid new artifacts being added to packages.

@xmfcx @lexavtanke what do you think about merging this as soon as possible?

**Comment by xmfcx** [comment]
@HansRobo @mitsudome-r @kminoda is this repository being utilized by some internal TIER IV repositories?

Do any of those repositories download during the `colcon build` process?

If not I would like to merge this.

**Comment by esteve** [comment]
@xmfcx `tensorrt_yolox` currently downloads from the internet, but the list of artifacts has been updated since we first submitted https://github.com/autowarefoundation/autoware/pull/3375, so I had to submit https://github.com/autowarefoundation/autoware/pull/3848 to update the ansible scripts

**Comment by xmfcx** [comment]
Also I've asked ChatGPT for a solution to see if there are any other way of doing it and it recommended following:
https://chat.openai.com/share/10110835-5bbc-48b0-91b3-299c62290fcf

```
   - name: Disable Internet (DNS method)
     run: echo "nameserver 0.0.0.0" | sudo tee /etc/resolv.conf
     shell: bash

   - name: Build
     run: |
       colcon build --event-handlers console_cohesion+ \
         --packages-above-and-dependencies ${{ inputs.target-packages }} \
         --cmake-args -DCMAKE_BUILD_TYPE=${{ inputs.cmake-build-type }} \
         --mixin coverage-gcc coverage-pytest compile-commands
     shell: bash

   - name: Restore Internet (DNS method)
     if: always()
     run: |
       echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
     shell: bash
```

I didn't try it but separating the disable internet and restore internet into separate items might make it more readable. I'm not aware of further implications of this change, please just treat it as a suggestion.

**Comment by esteve** [comment]
@xmfcx I prefer using the `nsswitch` method because we make sure that even if `/etc/resolv.conf` gets updated (e.g. via dhcp), we won't be using it

**Comment by esteve** [comment]
@xmfcx I don't think it's needed, because if `colcon build` fails, none of the other steps will run

**Review by xmfcx — APPROVED** [review]
I approve this to prevent additional changes being made which downloads artifacts during build process. Any repo will need to update their action version anyways to have these applied anyways.

**Comment by esteve** [comment]
@xmfcx thanks!

**Pull request merged**
