### PR TITLE
ci(pre-commit): fix pre-commit-config.yaml for pre-commit.ci

### PR DESCRIPTION
**Pull request by kenji-miyake**
To fix this error.
https://results.pre-commit.ci/run/github/429694607/1638877268.AkhVVtz6SGiwbOWUN8pigw

### CODE REVIEW

**Comment by kenji-miyake** [comment]
Worked.
https://results.pre-commit.ci/run/github/429694607/1638878229.bNjS1M6nSuqbWYGoe_LJFg

**Comment by kenji-miyake** [comment]
I'm not sure why pre-commit.ci will replace spaces into tabs... :thinking:

**Comment by kenji-miyake** [comment]
ad65c6d72f92cafa87266f10b08042e142c8b9b0 is for the consistency between local and CI result.

**Review by KeisukeShima — APPROVED** [review]

**Comment by kenji-miyake** [comment]
Oh, it seems `Go` is old. Will fix it later.
image

**Comment by kenji-miyake** [comment]
Updated `Go` in #7, so I'll merge this.

**Pull request merged**
