### PR TITLE
fix(delete-closed-pr-docs): remove PR directory when there is no corresponding PR

### LINKED ISSUE #79: [delete-closed-pr-docs] Fix errors on forks
https://github.com/kenji-miyake/autoware.universe/runs/5189322226?check_suite_focus=true

### PR DESCRIPTION
**Pull request by KeisukeShima**
Signed-off-by: Keisuke Shima <19993104+KeisukeShima@users.noreply.github.com>

## Description

Closes #79 
(The description is in issue.)

## Pre-review checklist for the PR author

PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

Reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has the write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by KeisukeShima** [comment]
Is the title too long?

**Comment by kenji-miyake** [comment]
Yes, you have to manually fix it. :pleading_face:

**Comment by KeisukeShima** [comment]
> Yes, you have to manually fix it. pleading_face

I see. Thanks!

**Comment by kenji-miyake** [comment]
I slightly changed the title.

**Review by kenji-miyake — APPROVED** [review]

**Pull request merged**
