### PR TITLE
feat(deploy-docs): add mkdocs-video

### PR DESCRIPTION
**Pull request by xmfcx**
Signed-off-by: M. Fatih Cırıt <mfc@leodrive.ai>

## Description

Let's support embedded videos in our documentation.

https://pypi.org/project/mkdocs-video/

Related to: https://github.com/autowarefoundation/autoware-documentation/pull/281/files#r1056538759

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by xmfcx** [comment]
As https://github.com/autowarefoundation/autoware-github-actions/pull/164 is merged, I got confused.

Should I add a `.github/mkdocs-requirements.txt` in https://github.com/autowarefoundation/autoware-documentation/ instead? @kenji-miyake

**Comment by kenji-miyake** [comment]
> Should I add a .github/mkdocs-requirements.txt in https://github.com/autowarefoundation/autoware-documentation/ instead? @kenji-miyake

@xmfcx No, adding here is okay because it's for Autoware Documentation.

https://github.com/autowarefoundation/autoware-github-actions/pull/164 is for non-Autoware documentation sites. They don't always use the same plugins as Autoware.

**Comment by kenji-miyake** [comment]
I'll wait for a reply to https://github.com/autowarefoundation/autoware-documentation/pull/281#discussion_r1057037028.
Although the PR was closed, I believe this PR may still be useful.

**Comment by xmfcx** [comment]
@kenji-miyake I think it's still better to add this plugin for future videos.

**Review by kenji-miyake — APPROVED** [review]

**Pull request merged**
