### PR TITLE
fix(remove-exec-depend): add `-` to the pattern of package names

### LINKED ISSUE #159: [remove-exec-depend] "-" not parsed in packages name
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

The regex here: https://github.com/autowarefoundation/autoware-github-actions/blob/9d8d2d8d1d0380c4a868c67c145051df4dacb048/remove-exec-depend/action.yaml#L9 doesn't match the character "-".
In the case of the autoware.universe repository, it leaves packages such as `libqt5-widgets` or `python3-matplotlib` as exec-depend.

It's not causing any problem at the moment, but it didn't look right.

### Expected behavior

Remove all exec-depend.

### Actual behavior

Some exec-depend are left.

### Steps to reproduce

In autoware.universe, run the action command: 
```sh
find . -name package.xml | xargs -I {} sed -i -rz "s|<exec_depend>\s*[a-zA-Z_0-9]+\s*</exec_depend>\n||g" {}
```
and grep for exec_depend:
```sh
grep -rn "<exec_depend>" $(find . -name package.xml)
```

### Versions

_No response_

### Possible causes

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kenji-miyake**
## Description

Resolves #159.
Also, the order of `0-9` and `_` was flipped for visibility.

My test result is here: https://github.com/autowarefoundation/autoware-github-actions/issues/159#issuecomment-1149189998

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kenji-miyake** [comment]
CI failed: https://github.com/autowarefoundation/autoware-github-actions/runs/6783082619?check_suite_focus=true#step:5:289

```
[1.638s] WARNING:colcon.colcon_core.verb.test:Test coverage will not be produced for package 'empty_target_python' since the pytest extension 'cov' was not found
```

It also fails with the `main` branch.
https://github.com/autowarefoundation/autoware-github-actions/runs/6783263865?check_suite_focus=true#step:5:294

@KeisukeShima Do you know the cause? :thinking:

**Comment by KeisukeShima** [comment]
> CI failed: https://github.com/autowarefoundation/autoware-github-actions/runs/6783082619?check_suite_focus=true#step:5:289
> 
> ```
> [1.638s] WARNING:colcon.colcon_core.verb.test:Test coverage will not be produced for package 'empty_target_python' since the pytest extension 'cov' was not found
> ```
> 
> It also fails with the `main` branch. https://github.com/autowarefoundation/autoware-github-actions/runs/6783263865?check_suite_focus=true#step:5:294
> 
> @KeisukeShima Do you know the cause? thinking

We may need to add the `pytest-cov` package. I assume the package we depend on has recently changed.

https://stackoverflow.com/questions/26589990/py-test-error-unrecognized-arguments-cov-ner-brands-cov-report-term-missi

**Comment by KeisukeShima** [comment]
@kenji-miyake The previous `ros:galactic` docker image contained `pytest-cov`.

```sh
$ docker images | grep ros | grep galactic
ros                                                                                       galactic                     1e1993371ff8   5 months ago    689MB
```

```sh
root@7e2f021257aa:/# dpkg -l | grep python3-pytest
ii  python3-pytest                                      4.6.9-1                              all          Simple, powerful testing in Python3
ii  python3-pytest-cov                                  2.8.1-1                              all          py.test plugin to produce coverage reports for Python3
```

**Comment by KeisukeShima** [comment]
Related? https://github.com/colcon/colcon-core/pull/508

**Pull request merged**
