### PR TITLE
fix: get-modified-packages.sh

### PR DESCRIPTION
**Pull request by h-ohta**
In previous implementation, `get-modified-packages.sh` can't get moified packages from the following structure of repository.
```
exapmple_launch$ tree 
.
├── CMakeLists.txt
├── launch
├── package.xml
├── README.md
...
```
This PR fixes this problem.

### CODE REVIEW

**Comment by kenji-miyake** [comment]
@h-ohta Thank you, but could you explain a bit more in detail?
- What was wrong?
- How did you test this?

**Comment by h-ohta** [comment]
@kenji-miyake Can I explain some repository in tier4 organization?

**Comment by kenji-miyake** [comment]
@h-ohta If it's public, it's fine. But if you can simplify and generalize the problem, it's the best.

**Comment by h-ohta** [comment]
@kenji-miyake 
I use https://github.com/tier4/lexus_description.iv as example repository.

- copy `get-modified-packages.sh` to `lexus_description.iv`
- do `./get-modified-packages.sh tier4/universe` and you get `::set-output name=modified-packages::` because you don't edit any.
- create a branch like `feature/test` and commit some file changes(ex. add some comment out to `package.xml`) 
- do  `./get-modified-packages.sh tier4/universe`, but you still get  `::set-output name=modified-packages::`.
- fix `get-modified-packages.sh` like this PR and do  `./get-modified-packages.sh tier4/universe`, you can get `::set-output name=modified-packages::lexus_description`.

Could you confirm this?

**Comment by kenji-miyake** [comment]
@h-ohta Could you create a test PR for that and link the failed workflow here?
Either in `lexus_description.iv` or a dedicated test repository is fine.

**Comment by h-ohta** [comment]
Oh, `lexus_description.iv` has no actions...

**Comment by h-ohta** [comment]
@kenji-miyake Actually, `lexus_description.iv` has old github actions, so I can't do what you say immediately.
Could you please follow my confirm procedure?

**Comment by h-ohta** [comment]
Or I I can your help, I can introduce latest github actions with sync-files...

**Comment by kenji-miyake** [comment]
Why don't you update the workflow? :thinking: 
I'm sorry, I can't spare much time for this, so please make the problem more clear and simple.

**Comment by kenji-miyake** [comment]
I always do so, too.
I believe it's a manner for contributors. Let's reduce the load of maintainers.

**Comment by h-ohta** [comment]
@kenji-miyake I got workflow result https://github.com/tier4/lexus_description.iv/runs/5088535135?check_suite_focus=true#step:7:1.
PR is https://github.com/tier4/lexus_description.iv/pull/9.
Now, I editted to package.xml(only add comments...), but get-modifired-packages.sh has no result.

**Comment by kenji-miyake** [comment]
@h-ohta Thank you for your clear explanation! I can understand the problem.

However, I believe this can be fixed with less diff.
It seems you did some refactoring with this fix, so could you minimize your diff?
Refactoring should be done in another PR.

**Comment by kenji-miyake** [comment]
Also if possible, could you write a test for this behavior?

**Comment by h-ohta** [comment]
@kenji-miyake 
OK. I'll make another PR to resolve with less diff.

> could you write a test for this behavior?

Could you tell me some examples?

**Comment by kenji-miyake** [comment]
I cannot show very concrete examples, but like this.
https://github.com/autowarefoundation/autoware-github-actions/blob/349f213850c20738a5bc67a2489c271ca6e33e6f/.github/workflows/test-composite-actions.yaml

**Comment by h-ohta** [comment]
@kenji-miyake I created https://github.com/autowarefoundation/autoware-github-actions/pull/61.
However, I have no idea for test... It seems to be difficult...

**Comment by kenji-miyake** [comment]
@h-ohta Thank you! Then, can you close this?

> However, I have no idea for test... It seems to be difficult...

That's fine! I'll manually test for now.

**Comment by h-ohta** [comment]
If we test this behavior, I suppose we have to prepare test repository which has the directory structure like `lexus_description.iv` and the branch with some changes in this organization.

**Comment by kenji-miyake** [comment]
Yes. Or we can create such a repository in the CI steps.

https://github.com/autowarefoundation/autoware-github-actions/blob/349f213850c20738a5bc67a2489c271ca6e33e6f/.github/workflows/test-composite-actions.yaml#L72

**Comment by kenji-miyake** [comment]
I believe we can close this. If there are some problems, feel free to reopen this.

**Pull request closed without merging**
