### PR TITLE
fix(get-modified-packages): fix a bug with top-level project repositories

### PR DESCRIPTION
**Pull request by h-ohta**
This PR is the solution same as #59 with less diff.

### CODE REVIEW

**Comment by kenji-miyake** [comment]
How to reproduce the problem:

```sh-session
cd /tmp
git clone git@github.com:tier4/lexus_description.iv.git
git clone git@github.com:autowarefoundation/autoware-github-actions.git
cd lexus_description.iv
echo "" >> package.xml
echo "" >> urdf/vehicle.xacro
git add .
git commit -m "tmp"
../autoware-github-actions/get-modified-packages/get-modified-packages.sh HEAD~
```

**Comment by kenji-miyake** [comment]
I believe this is the minimal diff. @h-ohta How do you feel about it?

```diff
diff --git a/get-modified-packages/get-modified-packages.sh b/get-modified-packages/get-modified-packages.sh
index 39ad852..7473819 100755
--- a/get-modified-packages/get-modified-packages.sh
+++ b/get-modified-packages/get-modified-packages.sh
@@ -56,7 +56,7 @@ modified_files=$(git diff --name-only "$base_branch"...HEAD)
 # Find modified packages
 modified_package_dirs=()
 for modified_file in $modified_files; do
-    modified_package_dir=$(find_package_dir "$modified_file")
+    modified_package_dir=$(find_package_dir "$(readlink -f $modified_file)")
 
     if [ "$modified_package_dir" != "" ]; then
         modified_package_dirs+=("$modified_package_dir")
```

**Comment by h-ohta** [comment]
@kenji-miyake It seems good.

**Comment by kenji-miyake** [comment]
Okay then, I'll consider another way a bit more and will fix the code later.

**Comment by kenji-miyake** [comment]
I think this is the best way.

image

**Review by kenji-miyake — APPROVED** [review]
@h-ohta Could you take a look, please?

**Comment by h-ohta** [comment]
@kenji-miyake It works.

**Comment by kenji-miyake** [comment]
Thank you for your contribution! I'll merge this. :smile:

**Pull request merged**
