### PR TITLE
ci: add test for colcon-build-and-test

### PR DESCRIPTION
**Pull request by KeisukeShima**
Related #35 

Signed-off-by: Keisuke Shima <19993104+KeisukeShima@users.noreply.github.com>

### CODE REVIEW

**Review by kenji-miyake — APPROVED** [review]

**Comment by KeisukeShima** [comment]
This workflow can detect #29 #30
But cannot detect #28 #34

**Comment by kenji-miyake** [comment]
Will you add other tests in this PR?

**Comment by KeisukeShima** [comment]
@kenji-miyake Umm, I think it's a limitation. I'm writing this here to keep it in the back of my mind.
To reproduce the error, #28 needs composite dependency and #34 needs ARM64 runner.

**Comment by kenji-miyake** [comment]
Okay, then let's merge this for now.

**Pull request merged**
