### PR TITLE
chore: sync issue and PR templates

### PR DESCRIPTION
**Pull request by kenji-miyake**
Sync files that will be added in https://github.com/autowarefoundation/autoware/pull/56.

### CODE REVIEW

**Comment by kenji-miyake** [comment]
@xmfcx Could you merge this and run the workflow `sync-files` as a practice?

**Review by xmfcx — APPROVED** [review]

**Comment by xmfcx** [comment]
> @xmfcx Could you merge this and run the workflow `sync-files` as a practice?

@kenji-miyake I think it worked: https://github.com/autowarefoundation/autoware.core/actions/workflows/sync-files.yaml

**Comment by kenji-miyake** [comment]
@xmfcx Oh, you have to run it in this repository!
https://github.com/autowarefoundation/autoware-github-actions/actions/workflows/sync-files.yaml

**Comment by xmfcx** [comment]
> @xmfcx Oh, you have to run it in this repository! https://github.com/autowarefoundation/autoware-github-actions/actions/workflows/sync-files.yaml

Then why do we have it in the  https://github.com/autowarefoundation/autoware.core/actions/workflows/sync-files.yaml repository?

**Comment by kenji-miyake** [comment]
The workflow exists in each repository and each has different settings.
For example, a documentation repository doesn't require `clang-tidy`.

**Comment by kenji-miyake** [comment]
Please see here for the design concept.
https://github.com/autowarefoundation/autoware-github-actions/pull/26#issue-1111974989

**Comment by kenji-miyake** [comment]
Worked, great! https://github.com/autowarefoundation/autoware-github-actions/pull/102

**Comment by xmfcx** [comment]
> Worked, great! #102

Oh I thought it'd automatically merge. It created a PR :o

**Comment by kenji-miyake** [comment]
We can do that, but I don't do it now because I'd like to confirm the change just in case.

**Comment by kenji-miyake** [comment]
For example, I could find a mistake here. It was not `config.yaml` but `config.yml`. (There was a limitation. :pleading_face: )
image

**Comment by xmfcx** [comment]
How does this repository's action know which other uses this workflow? And it creates PR's for those specific repos?

Are these connections managed by the https://github.com/apps/awf-autoware-bot ?

**Comment by xmfcx** [comment]
> How does this repository's action know which other repos use this workflow? And it creates PR's for those specific repos?
> 
> Are these connections managed by the https://github.com/apps/awf-autoware-bot ?

Hmm it actually creates the PR in this repository 🤔

**Comment by kenji-miyake** [comment]
I think it doesn't have to know that. :thinking: 
The repository only needs to know the workflows that run in the repository itself.

`sync-files` workflow will visit other repositories and copy files.

**Comment by xmfcx** [comment]
> `sync-files` workflow will visit other repositories and copy files.

How does it know which repos to visit?

**Comment by kenji-miyake** [comment]
It's in the config file!
https://github.com/autowarefoundation/autoware-github-actions/blob/9217e160a1fb6dd17c2513a9c26e66f8292ff5f9/.github/sync-files.yaml#L1

**Comment by xmfcx** [comment]
> It's in the config file!
> 
> https://github.com/autowarefoundation/autoware-github-actions/blob/9217e160a1fb6dd17c2513a9c26e66f8292ff5f9/.github/sync-files.yaml#L1

But it doesn't have https://github.com/autowarefoundation/autoware.core in the list?

**Comment by kenji-miyake** [comment]
Right. So it doesn't sync from `autoware.core`.

**Comment by xmfcx** [comment]
@kenji-miyake I've created a diagram that contains the linkage between some packages through the sync-files.yaml:

https://drive.google.com/file/d/1jB09GtBXpPv0oCh9hqGKK4WaxLtqHYS8/view?usp=sharing

To me it looks confusing. Why isn't [autoware-github-actions](https://github.com/autowarefoundation/autoware-github-actions/blob/main/.github/sync-files.yaml) updating [autoware-documentation](https://github.com/autowarefoundation/autoware-documentation/blob/main/.github/sync-files.yaml)

And many other packages update the autoware and autoware_common.

And [autoware_common](https://github.com/autowarefoundation/autoware_common/blob/main/.github/sync-files.yaml) updates autoware.

**Comment by kenji-miyake** [comment]
> To me it looks confusing. Why isn't [autoware-github-actions](https://github.com/autowarefoundation/autoware-github-actions/blob/main/.github/sync-files.yaml) updating [autoware-documentation](https://github.com/autowarefoundation/autoware-documentation/blob/main/.github/sync-files.yaml) ?

:thinking: ?
Since it just pulls from repositories listed in `sync-files.yaml`, `autoware-github-actions` and `autoware-documentation` have no relationship.
It doesn't push.

**Comment by xmfcx** [comment]
chrome_2022-03-13_11-02-25

@kenji-miyake hmm so the file update flow is in the reverse direction.

**Comment by xmfcx** [comment]
So if we update some of these files in `autoware` repository, we need to run the workflow in all the other repositories including:
- autoware-documentation
- autoware_common
- autoware.core
- autoware-github-actions
- sample_sensor_kit_launch
- sample_vehicle_launch
- autoware_individual_params
- ...

So that they receive the updates right?

Or the sync will happen everyday with the cron job right?

**Comment by kenji-miyake** [comment]
Yes, right. But it will run daily by corn.
https://github.com/autowarefoundation/autoware-github-actions/blob/9217e160a1fb6dd17c2513a9c26e66f8292ff5f9/.github/workflows/sync-files.yaml#L5

**Comment by xmfcx** [comment]
Maybe we should've made it sync a folder instead. Because this way if we want to sync an extra file across repositories, we will need to add it to each of their [sync-files.yaml](https://github.com/autowarefoundation/autoware_common/blob/main/.github/sync-files.yaml) files.

This doesn't feel like DRY, so many repeated instructions/configurations.

**Comment by xmfcx** [comment]
Imagine the burden of renaming a [single file](https://github.com/autowarefoundation/autoware_common/blob/main/.github/sync-files.yaml) in the main autoware repository, all of the other repos will need to update their corresponding file names to sync.

**Comment by kenji-miyake** [comment]
We don't always want to sync the entire directory.
It's the tradeoff. By syncing directories, it may cause different problems.
For example, sometimes undesired files might be copied.

> This doesn't feel like DRY, so many repeated instructions/configurations.

Anytime you can propose a change and send a PR to improve it. :smile: 

> Imagine the burden of renaming a [single file](https://github.com/autowarefoundation/autoware_common/blob/main/.github/sync-files.yaml) in the main autoware repository, all of the other repos will need to update their corresponding file names to sync.

Yes, but it's a rare case.
Also, what do you recommend instead of doing that?
Could you show me an alternative config file notation?

**Comment by xmfcx** [comment]
@kenji-miyake do you think we could utilize this functionality: https://github.com/Redocly/repo-file-sync-action#sync-the-same-files-to-multiple-repositories ?

So we can create a group and refer to that to avoid repeating the same file lists across repositories.

**Comment by kenji-miyake** [comment]
@xmfcx Within the AWF, yes it's possible.
But considering forks by many companies, I prefer the current way.

**Comment by xmfcx** [comment]
> @xmfcx Within the AWF, yes it's possible. But considering forks by many companies, I prefer the current way.

I understand, this is why you avoided the `dest:` and only used `source:` it makes sense.

**Comment by kenji-miyake** [comment]
Actually, I think `dest` is just for renaming synced files.
But yeah, it's why I used the pull-based workflow rather than the push-based one that cannot control outside the organization.

**Pull request merged**
